// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://dtqxhwmkfygtaiijjyle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0cXhod21rZnlndGFpaWpqeWxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUzODMyMzMsImV4cCI6MjA5MDk1OTIzM30.OQ_1oZDRwSud9avHLsEOb4XlQMsTzNTkie7Am-u1Bow";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});